### ISSUE TITLE
Updating values via JS does not update the track

### ISSUE THREAD

**Issue by kosso** [samuelcarreira/webkit-input-range-fill-lower#2]
Hi. 
Thanks for this hack. I really am shocked to see that we still need to do this in 2019 for Chrome! (Unless I missed the memo!) 

But I found that if you try to update input value with Javascript (eg: using as a music progress slider), the position of the thumb updates OK, but the position of the upper and lower tracks don't. 

They only seem to move if I manually slider the slider. 

Any ideas of any workarounds to this?

Thanks!

**Comment by samuelcarreira** [comment]
Hi @kosso, can you provide more details about the issue like a sample source code?

**Comment by kosso** [comment]
Argh! Sorry, I'm a buffoon!  I forgot the JS requirement! 

For some reason I thought this was CSS only. 

I have now added the `writeStyle` method where I need it! 

Sorry! 
;)

**Comment by samuelcarreira** [comment]
No problem, you can modify the script to use only CSS like some progress bar scripts out there, but because you commonly use JS to update or read the value, I only used JS when I developed this very simple project.

Regards,
Samuel
